import torch
import logging

logger = logging.getLogger(__name__)

print("遍历模型的所有权重:")
print("-" * 50)


model_pth_path = '/home/ray/deploy/fireredasr_models/FireRedASR-LLM-L/model.pth.tar'
try:
    package = torch.load(model_pth_path, map_location=lambda storage, loc: storage, weights_only=False)
except Exception as e:
    logger.error(f"Failed to load {model_pth_path}: {e}")
    raise

state_dict = package['model_state_dict']

# 遍历字典中的每一个项目 (名称, 权重张量)
for param_name, param_tensor in state_dict.items():
    # 1. 打印权重的名字
    print(f"权重名称 (Name): {param_name}")
    
    # # 2. (可选) 打印权重的形状 (Shape)，这对于调试模型结构非常有帮助
    # print(f"  - 形状 (Shape): {param_tensor.shape}")
    
    # # 3. (可选) 打印权重的数据类型 (Data Type)
    # print(f"  - 类型 (Dtype): {param_tensor.dtype}")
    # print("-" * 50)


"""
results:
遍历模型的所有权重:
--------------------------------------------------
权重名称 (Name): encoder.positional_encoding.pe
权重名称 (Name): encoder.input_preprocessor.conv.0.weight
权重名称 (Name): encoder.input_preprocessor.conv.0.bias
权重名称 (Name): encoder.input_preprocessor.conv.2.weight
权重名称 (Name): encoder.input_preprocessor.conv.2.bias
权重名称 (Name): encoder.input_preprocessor.out.weight
权重名称 (Name): encoder.input_preprocessor.out.bias
权重名称 (Name): encoder.layer_stack.0.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.0.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.0.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.0.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.0.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.0.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.0.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.0.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.0.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.0.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.0.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.0.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.0.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.0.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.0.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.0.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.0.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.0.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.0.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.0.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.0.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.0.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.0.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.0.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.0.layer_norm.weight
权重名称 (Name): encoder.layer_stack.0.layer_norm.bias
权重名称 (Name): encoder.layer_stack.1.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.1.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.1.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.1.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.1.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.1.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.1.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.1.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.1.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.1.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.1.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.1.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.1.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.1.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.1.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.1.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.1.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.1.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.1.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.1.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.1.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.1.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.1.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.1.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.1.layer_norm.weight
权重名称 (Name): encoder.layer_stack.1.layer_norm.bias
权重名称 (Name): encoder.layer_stack.2.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.2.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.2.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.2.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.2.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.2.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.2.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.2.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.2.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.2.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.2.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.2.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.2.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.2.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.2.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.2.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.2.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.2.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.2.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.2.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.2.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.2.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.2.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.2.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.2.layer_norm.weight
权重名称 (Name): encoder.layer_stack.2.layer_norm.bias
权重名称 (Name): encoder.layer_stack.3.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.3.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.3.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.3.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.3.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.3.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.3.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.3.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.3.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.3.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.3.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.3.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.3.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.3.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.3.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.3.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.3.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.3.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.3.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.3.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.3.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.3.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.3.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.3.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.3.layer_norm.weight
权重名称 (Name): encoder.layer_stack.3.layer_norm.bias
权重名称 (Name): encoder.layer_stack.4.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.4.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.4.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.4.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.4.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.4.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.4.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.4.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.4.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.4.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.4.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.4.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.4.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.4.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.4.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.4.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.4.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.4.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.4.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.4.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.4.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.4.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.4.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.4.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.4.layer_norm.weight
权重名称 (Name): encoder.layer_stack.4.layer_norm.bias
权重名称 (Name): encoder.layer_stack.5.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.5.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.5.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.5.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.5.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.5.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.5.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.5.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.5.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.5.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.5.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.5.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.5.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.5.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.5.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.5.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.5.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.5.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.5.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.5.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.5.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.5.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.5.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.5.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.5.layer_norm.weight
权重名称 (Name): encoder.layer_stack.5.layer_norm.bias
权重名称 (Name): encoder.layer_stack.6.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.6.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.6.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.6.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.6.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.6.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.6.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.6.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.6.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.6.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.6.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.6.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.6.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.6.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.6.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.6.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.6.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.6.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.6.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.6.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.6.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.6.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.6.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.6.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.6.layer_norm.weight
权重名称 (Name): encoder.layer_stack.6.layer_norm.bias
权重名称 (Name): encoder.layer_stack.7.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.7.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.7.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.7.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.7.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.7.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.7.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.7.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.7.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.7.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.7.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.7.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.7.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.7.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.7.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.7.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.7.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.7.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.7.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.7.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.7.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.7.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.7.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.7.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.7.layer_norm.weight
权重名称 (Name): encoder.layer_stack.7.layer_norm.bias
权重名称 (Name): encoder.layer_stack.8.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.8.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.8.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.8.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.8.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.8.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.8.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.8.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.8.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.8.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.8.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.8.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.8.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.8.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.8.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.8.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.8.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.8.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.8.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.8.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.8.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.8.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.8.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.8.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.8.layer_norm.weight
权重名称 (Name): encoder.layer_stack.8.layer_norm.bias
权重名称 (Name): encoder.layer_stack.9.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.9.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.9.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.9.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.9.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.9.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.9.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.9.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.9.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.9.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.9.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.9.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.9.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.9.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.9.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.9.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.9.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.9.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.9.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.9.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.9.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.9.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.9.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.9.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.9.layer_norm.weight
权重名称 (Name): encoder.layer_stack.9.layer_norm.bias
权重名称 (Name): encoder.layer_stack.10.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.10.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.10.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.10.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.10.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.10.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.10.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.10.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.10.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.10.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.10.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.10.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.10.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.10.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.10.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.10.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.10.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.10.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.10.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.10.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.10.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.10.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.10.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.10.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.10.layer_norm.weight
权重名称 (Name): encoder.layer_stack.10.layer_norm.bias
权重名称 (Name): encoder.layer_stack.11.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.11.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.11.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.11.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.11.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.11.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.11.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.11.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.11.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.11.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.11.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.11.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.11.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.11.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.11.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.11.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.11.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.11.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.11.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.11.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.11.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.11.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.11.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.11.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.11.layer_norm.weight
权重名称 (Name): encoder.layer_stack.11.layer_norm.bias
权重名称 (Name): encoder.layer_stack.12.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.12.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.12.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.12.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.12.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.12.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.12.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.12.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.12.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.12.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.12.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.12.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.12.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.12.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.12.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.12.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.12.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.12.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.12.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.12.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.12.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.12.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.12.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.12.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.12.layer_norm.weight
权重名称 (Name): encoder.layer_stack.12.layer_norm.bias
权重名称 (Name): encoder.layer_stack.13.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.13.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.13.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.13.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.13.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.13.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.13.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.13.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.13.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.13.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.13.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.13.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.13.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.13.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.13.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.13.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.13.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.13.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.13.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.13.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.13.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.13.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.13.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.13.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.13.layer_norm.weight
权重名称 (Name): encoder.layer_stack.13.layer_norm.bias
权重名称 (Name): encoder.layer_stack.14.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.14.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.14.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.14.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.14.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.14.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.14.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.14.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.14.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.14.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.14.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.14.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.14.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.14.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.14.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.14.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.14.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.14.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.14.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.14.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.14.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.14.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.14.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.14.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.14.layer_norm.weight
权重名称 (Name): encoder.layer_stack.14.layer_norm.bias
权重名称 (Name): encoder.layer_stack.15.ffn1.net.0.weight
权重名称 (Name): encoder.layer_stack.15.ffn1.net.0.bias
权重名称 (Name): encoder.layer_stack.15.ffn1.net.1.weight
权重名称 (Name): encoder.layer_stack.15.ffn1.net.1.bias
权重名称 (Name): encoder.layer_stack.15.ffn1.net.4.weight
权重名称 (Name): encoder.layer_stack.15.ffn1.net.4.bias
权重名称 (Name): encoder.layer_stack.15.mhsa.pos_bias_u
权重名称 (Name): encoder.layer_stack.15.mhsa.pos_bias_v
权重名称 (Name): encoder.layer_stack.15.mhsa.w_qs.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.w_ks.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.w_vs.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_q.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_q.bias
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_k.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_k.bias
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_v.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.layer_norm_v.bias
权重名称 (Name): encoder.layer_stack.15.mhsa.fc.weight
权重名称 (Name): encoder.layer_stack.15.mhsa.linear_pos.weight
权重名称 (Name): encoder.layer_stack.15.conv.pre_layer_norm.weight
权重名称 (Name): encoder.layer_stack.15.conv.pre_layer_norm.bias
权重名称 (Name): encoder.layer_stack.15.conv.pointwise_conv1.weight
权重名称 (Name): encoder.layer_stack.15.conv.depthwise_conv.weight
权重名称 (Name): encoder.layer_stack.15.conv.batch_norm.weight
权重名称 (Name): encoder.layer_stack.15.conv.batch_norm.bias
权重名称 (Name): encoder.layer_stack.15.conv.pointwise_conv2.weight
权重名称 (Name): encoder.layer_stack.15.ffn2.net.0.weight
权重名称 (Name): encoder.layer_stack.15.ffn2.net.0.bias
权重名称 (Name): encoder.layer_stack.15.ffn2.net.1.weight
权重名称 (Name): encoder.layer_stack.15.ffn2.net.1.bias
权重名称 (Name): encoder.layer_stack.15.ffn2.net.4.weight
权重名称 (Name): encoder.layer_stack.15.ffn2.net.4.bias
权重名称 (Name): encoder.layer_stack.15.layer_norm.weight
权重名称 (Name): encoder.layer_stack.15.layer_norm.bias
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.0.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.1.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.2.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.3.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.4.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.5.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.6.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.7.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.8.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.9.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.10.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.11.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.12.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.13.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.14.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.15.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.16.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.17.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.18.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.19.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.20.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.21.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.22.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.23.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.24.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.25.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.26.mlp.down_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.q_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.q_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.k_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.k_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.v_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.v_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.o_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.self_attn.o_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.gate_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.gate_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.up_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.up_proj.lora_B.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.down_proj.lora_A.default.weight
权重名称 (Name): llm.base_model.model.model.layers.27.mlp.down_proj.lora_B.default.weight
权重名称 (Name): encoder_projector.linear1.weight
权重名称 (Name): encoder_projector.linear1.bias
权重名称 (Name): encoder_projector.linear2.weight
权重名称 (Name): encoder_projector.linear2.bias
"""